In [1]:
import pandas as pd

In [23]:
disease_signatures = pd.read_table("data/Disease_Signatures_MECFS.tsv", sep="\t")
heads = disease_signatures.columns
disease_signatures[heads[1]] = disease_signatures[heads[1]].str.split(", ")
disease_signatures[heads[2]] = disease_signatures[heads[2]].str.split(", ")

In [26]:
snp_table = pd.read_table("data/SNP_Table_MECFS.tsv", sep="\t")
snp_table

,SNP ID,Chromosome,Position in Build GRCh37,Variants (Ref/Alt),Critical SNP,GWAS p-value (PLINK),Gene(s) mapped based on genomic position,SNP to Gene mapping
0,rs41306603,1,33321877,A/C,1,0.542700,S100PBP,genebody
1,rs2985754,1,39053684,T/C,0,0.000646,NaN,NaN
2,rs946448,1,54661150,C/T,0,0.041750,"CYB5RL, AL357673.1, MRPL37",genebody
3,rs12562306,1,54662686,G/A,0,0.039590,"CYB5RL, AL357673.1, MRPL37",genebody
4,rs17571877,1,73987668,G/A,0,0.368700,LINC02238,closest
...,...,...,...,...,...,...,...,...
194,rs10470164,21,33384319,T/C,0,0.615600,HUNK,genebody
195,rs13047599,21,34926260,T/C,0,0.159700,SON,genebody
196,rs2309099,21,43074513,T/G,0,0.004779,NaN,NaN
197,rs11910362,21,44042101,T/C,0,0.041830,NaN,NaN
198,rs5747306,22,18128960,A/G,0,0.000648,BCL2L13,genebody

In [29]:
metabolites = pd.read_excel("data/Hoel_et_al_metabolites.xlsx")
metabolites

,SUPPLEMENTARY FILE 2 - METABOLON CLP DATA,Unnamed: 1
0,NaN,NaN
1,SHEET,CONTENT
2,1.Suppl 2 content,Overview of the content in Supplermentary file 2
3,2.FC & Stats,Curated CLP metabolite data ME-ALL-M1-M2-M3 vs HC
4,3.FC CLP classes,Total lipid class concentrations (calculated/e...
5,4.psign MEall,"p-significant metabolites, MEall vs HC"
6,5.psign Uniform,"p-significant metabolites, Uniform in ME-M1 an..."
7,6.psign ME-M1,"p-significant metabolites, ME-M1 vs HC, UP & D..."
8,7.psign ME-M2,"p-significant metabolites, ME-M2 vs HC, UP & D..."
9,8.psign ME-M3,"p-significant metabolites, ME-M3 vs HC, UP & D..."
10,9.FA Conc,"Total fatty acid concentration, per class, cal..."
11,10.FA Mol%,"Fatty acid composition, per class, calculated ..."

In [33]:
metabolites.head()

,SUPPLEMENTARY FILE 2 - METABOLON CLP DATA,Unnamed: 1
0,NaN,NaN
1,SHEET,CONTENT
2,1.Suppl 2 content,Overview of the content in Supplermentary file 2
3,2.FC & Stats,Curated CLP metabolite data ME-ALL-M1-M2-M3 vs HC
4,3.FC CLP classes,Total lipid class concentrations (calculated/e...